package RangerCaptain.util;

import RangerCaptain.cardmods.fusion.AdeptileMod;
import RangerCaptain.cardmods.fusion.AllseerMod;
import RangerCaptain.cardmods.fusion.KhufoMod;
import RangerCaptain.cardmods.fusion.MardiusaMod;
import RangerCaptain.cardmods.fusion.abstracts.AbstractFusionMod;

import java.util.HashMap;

import static RangerCaptain.util.MonsterEnum.*;

public class FusionCardModData {
    public static final HashMap<MonsterEnum, AbstractFusionMod> MOD_MAP = new HashMap<>();

    public static void add(MonsterEnum monster, AbstractFusionMod mod) {
        MOD_MAP.put(monster, mod);
    }

    static {
        add(ADEPTILE, new AdeptileMod());
        add(AEROBOROS, null);
        add(ALLSEER, new AllseerMod());
        add(AMPHARE, null);
        add(ANATHEMA, null);
        add(APOCROWLYPSE, null);
        add(ARKIDD, null);
        add(ARTILLEREX, null);
        add(AURICLAW, null);
        add(AVEREVOIR, null);
        add(BANSHEEP, null);
        add(BEANSTALKER, null);
        add(BINTERLOPER, null);
        add(BINVADER, null);
        add(BLOSSOMAW, null);
        add(BLUNDERBUSK, null);
        add(BOLTAM, null);
        add(BRAXSUIT, null);
        add(BRUSHROOM, null);
        add(BULLETINO, null);
        add(BURNACE, null);
        add(BUSHEYE, null);
        add(CANDEVIL, null);
        add(CAPRICORPSE, null);
        add(CARNIVIPER, null);
        add(CATFIVE, null);
        add(CHARLEQUIN, null);
        add(CLOCKSLEY, null);
        add(CLUCKABILLY, null);
        add(COALDRON, null);
        add(CRYOSHEAR, null);
        add(DANDYLION, null);
        add(DECIBELLE, null);
        add(DIVEAL, null);
        add(DIVEBERG, null);
        add(DJINN_ENTONIC, null);
        add(DOMINOTH, null);
        add(DRACULEAF, null);
        add(ELFLESS, null);
        add(FAERIOUS, null);
        add(FAUCETEAR, null);
        add(FERRICLAW, null);
        add(FLAPWOODS, null);
        add(FOLKLORD, null);
        add(FORTIWINX, null);
        add(FOUNTESS, null);
        add(FRAGLIACCI, null);
        add(FRILLYPAD, null);
        add(FUNGOGH, null);
        add(GALAGOR, null);
        add(GEARYU, null);
        add(GLAISTAIN, null);
        add(GRAMPUS, null);
        add(GUMBAAL, null);
        add(HAUNTOME, null);
        add(HEDGEHERNE, null);
        add(HOPSKIN, null);
        add(HUNTORCH, null);
        add(ICEPECK, null);
        add(JELLYTON, null);
        add(JORMUNGOLD, null);
        add(JUMPKIN, null);
        add(KHEPRI, null);
        add(KHUFO, new KhufoMod());
        add(KINGRAVE, null);
        add(KIRIKURI, null);
        add(KITTELLY, null);
        add(KUNEKO, null);
        add(LAPACITOR, null);
        add(LILIGATOR, null);
        add(LITTLERED, null);
        add(LOBSTACLE, null);
        add(MACABRA, null);
        add(MAGIKRAB, null);
        add(MAJORTOM, null);
        add(MALCHEMY, null);
        add(MANISPEAR, null);
        add(MARDIUSA, new MardiusaMod());
        add(MASCOTORN, null);
        add(MASCOTOY, null);
        add(MASQUERATTLE, null);
        add(MIASMODEUS, null);
        add(MINORTOM, null);
        add(MISS_MIMIC, null);
        add(MOTHMANIC, null);
        add(MUSKRATEER, null);
        add(NEVERMORT, null);
        add(PADPOLE, null);
        add(PALANGOLIN, null);
        add(PAWNDEAD, null);
        add(PICKSIE, null);
        add(PINBOLT, null);
        add(PLASMANTLER, null);
        add(POMBOMB, null);
        add(PONDWALKER, null);
        add(PUPPERCUT, null);
        add(PYROMELEON, null);
        add(QUEENYX, null);
        add(RAMTASM, null);
        add(RATCOUSEL, null);
        add(REGENSEA, null);
        add(RIPTERRA, null);
        add(ROBINDAM, null);
        add(ROCKERTRICE, null);
        add(ROSEHOOD, null);
        add(SALAMAGUS, null);
        add(SANZATIME, null);
        add(SCAMPIRE, null);
        add(SCARLETEETH, null);
        add(SCUBALRUS, null);
        add(SHARKTANKER, null);
        add(SHINING_KUNEKO, null);
        add(SIRENADE, null);
        add(SKELEVANGELIST, null);
        add(SMOGMAGOG, null);
        add(SNOOPIN, null);
        add(SOUTHPAW, null);
        add(SPARKTAN, null);
        add(SPIROUETTE, null);
        add(SPITZFYRE, null);
        add(SPOOKIONNA, null);
        add(SPRINGHEEL, null);
        add(SQUIREY, null);
        add(STARDIGRADE, null);
        add(TERRACOOKA, null);
        add(THWACKALOPE, null);
        add(TOKUSECT, null);
        add(TRAFFIKRAB, null);
        add(TRAPWURM, null);
        add(TRIPHINX, null);
        add(TWIRLIGIG, null);
        add(UMBRAHELLA, null);
        add(UNDYIN, null);
        add(VELOCIRIFLE, null);
        add(VENDEMON, null);
        add(WEEVILITE, null);
        add(WINGLOOM, null);
        add(WOOLTERGEIST, null);
        add(WYRMAW, null);
        add(ZEUSTRIKE, null);
        add(ZOMBLEAT, null);
    }
}
